FROM continuumio/miniconda
ADD . /app
# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 parallel && rm -rf /var/lib/apt/lists/*
RUN conda update -y conda
RUN conda install -c aroth85 strelka

RUN conda install -c conda-forge intervaltree
RUN cp /app/run_strelka /opt/conda/bin && chmod u+x /opt/conda/bin/run_strelka
# Make port 80 available to the world outside this container
EXPOSE 80

# set env name
ENV NAME samtools
ENV PATH="/opt/conda/share/strelka-2.8.2-0/libexec/:${PATH}"
ENV STRELKA_SHARE_DIR '/opt/conda/share/strelka-2.8.2-0/'

CMD ["strelka"]
