# build on top of out base image
FROM continuumio/miniconda

# Install any needed packages specified in requirements.txt
RUN conda install -c shahcompbio museqportrait==0.99.13
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME museqportrait

# Run app.py when the container launches
CMD ["museqportrait"]
