FROM continuumio/miniconda3

# Install basic packages
RUN conda install -c shahcompbio pseudo_bulk_qc_html_report
RUN pip install -e git+https://github.com/shahcompbio/pypeliner.git@v0.5.20#egg=pypeliner
# Make port 80 available to the world outside this container
EXPOSE 80

# set env name
ENV NAME pseudo_bulk_qc_html_report

# Run python when the container launches
CMD ["R"]

