#Test dockerfile
# miniconda image with conda
FROM continuumio/miniconda

# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*
RUN conda update -y conda
RUN pip install GitPython 
RUN pip install awscli --upgrade
# Make port 80 available to the world outside this container
EXPOSE 80
CMD ["python"]
