FROM wgspipeline/python_wgs:v0.0.2

RUN apt-get update && apt install build-essential gcc -y && rm -rf /var/lib/apt/lists/*
RUN conda install -c bioconda -c dranew destruct==0.4.7 blossomv==2.04  -y
RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.5.14
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@v0.2.2
RUN rm -rf /opt/conda/lib/python2.7/site-packages/destruct* &&  pip install git+https://github.com/amcpherson/destruct.git@v0.4.7_pypeliner_latest

EXPOSE 80

ENV NAME destruct

CMD ["destruct"]
