# build on top of out base image
FROM wgscomputecr.azurecr.io/wgs/python_wgs:v0.0.1

# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt
RUN pip install git+https://dgrewal@svn.bcgsc.ca/bitbucket/scm/~dgrewal/vizutils.git

# Make port 80 available to the world outside this container

# Define environment variable

# Run app.py when the container launches
